import { Poppins } from "next/font/google";
import { Menu } from "./components/Menu";
import Footer from "./components/Footer";
import "./globals.css";

const poppins = Poppins({ subsets: ["latin"], weight: ["200", "400", "700"] });
const links = [
  { label: "Home", route: "/" },
  { label: "Proyectos", route: "/proyectos" },
  { label: "Cotización", route: "/cotizacion" },
];

export const metadata = {
  title: "Cocinas y decoraciones H&S",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="shorcut icon" href="/favicon.ico" />
      </head>
      <body className={poppins.className}>
        <header>
          <Menu links={links} />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
