import { Inter } from "next/font/google";
import { Menu } from "./components/Menu";
import Footer from "./components/Footer";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });
const links = [
  { label: "Home", route: "/" },
  { label: "Proyectos", route: "/proyectos" },
  { label: "Cotización", route: "/cotizacion" },
];

export const metadata = {
  title: "Cocinas y decoraciones H&S",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Menu links={links} />
        </header>
        {children}
        <Footer />
      </body>
    </html>
  );
}
